import 'package:evently/core/resources/assets_manager.dart';
import 'package:evently/data/dm/category.dart';
import 'package:flutter/material.dart';

class ConstantManager {
  static List<CategoryDM> categoriesWithAll = [
    CategoryDM(id: "1", name: "ALL", icon: Icons.clear_all_outlined),
    CategoryDM(id: "2",
        name: "Sport",
        icon: Icons.sports_baseball_outlined,
        imagePath: AssetsManager.sportsLight),
    CategoryDM(id: "3",
        name: "BirthDay",
        icon: Icons.celebration,
        imagePath: AssetsManager.birthDayLight),
    CategoryDM(id: "4",
        name: "Meeting",
        icon: Icons.meeting_room,
        imagePath: AssetsManager.meetingLight),
    CategoryDM(id: "5",
        name: "Gaming",
        icon: Icons.games_outlined,
        imagePath: AssetsManager.gamingLight),
    CategoryDM(id: "6",
        name: "Eating",
        icon: Icons.emoji_food_beverage,
        imagePath: AssetsManager.eatingLight),
    CategoryDM(id: "7",
        name: "Holiday",
        icon: Icons.holiday_village_outlined,
        imagePath: AssetsManager.holidayLight),
    CategoryDM(id: "8",
        name: "Exhibition",
        icon: Icons.museum,
        imagePath: AssetsManager.exhibitionLight),
    CategoryDM(id: "9",
        name: "WorkShop",
        icon: Icons.work_history,
        imagePath: AssetsManager.workshopLight),
    CategoryDM(id: "10",
        name: "BookClub",
        icon: Icons.book,
        imagePath: AssetsManager.bookClubLight),
  ];

  static List<CategoryDM> categories = [
    CategoryDM(id: "2",
        name: "Sport",
        icon: Icons.sports_baseball_outlined,
        imagePath: AssetsManager.sportsLight),
    CategoryDM(id: "3",
        name: "BirthDay",
        icon: Icons.celebration,
        imagePath: AssetsManager.birthDayLight),
    CategoryDM(id: "4",
        name: "Meeting",
        icon: Icons.meeting_room,
        imagePath: AssetsManager.meetingLight),
    CategoryDM(id: "5",
        name: "Gaming",
        icon: Icons.games_outlined,
        imagePath: AssetsManager.gamingLight),
    CategoryDM(id: "6",
        name: "Eating",
        icon: Icons.emoji_food_beverage,
        imagePath: AssetsManager.eatingLight),
    CategoryDM(id: "7",
        name: "Holiday",
        icon: Icons.holiday_village_outlined,
        imagePath: AssetsManager.holidayLight),
    CategoryDM(id: "8",
        name: "Exhibition",
        icon: Icons.museum,
        imagePath: AssetsManager.exhibitionLight),
    CategoryDM(id: "9",
        name: "WorkShop",
        icon: Icons.work_history,
        imagePath: AssetsManager.workshopLight),
    CategoryDM(id: "10",
        name: "BookClub",
        icon: Icons.book,
        imagePath: AssetsManager.bookClubLight),
  ];
}